// Package botApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package botApi

import (
	"time"
)

// ApiErrorResponse defines model for ApiErrorResponse.
type ApiErrorResponse struct {
	Code             *string   `json:"code,omitempty"`
	Description      *string   `json:"description,omitempty"`
	ExceptionMessage *string   `json:"exceptionMessage,omitempty"`
	ExceptionName    *string   `json:"exceptionName,omitempty"`
	Stacktrace       *[]string `json:"stacktrace,omitempty"`
}

// Event defines model for Event.
type Event struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description string    `json:"description"`
	Title       string    `json:"title"`
	Type        string    `json:"type"`
	Username    string    `json:"username"`
}

// UpdateResponse defines model for UpdateResponse.
type UpdateResponse struct {
	Data      []Event `json:"data"`
	Id        int64   `json:"id"`
	TgChatIds []int64 `json:"tgChatIds"`
	Url       string  `json:"url"`
}

// PostUpdatesJSONRequestBody defines body for PostUpdates for application/json ContentType.
type PostUpdatesJSONRequestBody = UpdateResponse
