// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: scrapper-api.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrapperAPI_RegisterChat_FullMethodName = "/scrapper.ScrapperAPI/RegisterChat"
	ScrapperAPI_DeleteChat_FullMethodName   = "/scrapper.ScrapperAPI/DeleteChat"
	ScrapperAPI_GetLinks_FullMethodName     = "/scrapper.ScrapperAPI/GetLinks"
	ScrapperAPI_AddLink_FullMethodName      = "/scrapper.ScrapperAPI/AddLink"
	ScrapperAPI_RemoveLink_FullMethodName   = "/scrapper.ScrapperAPI/RemoveLink"
)

// ScrapperAPIClient is the client API for ScrapperAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapperAPIClient interface {
	RegisterChat(ctx context.Context, in *RegisterChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
	AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
}

type scrapperAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperAPIClient(cc grpc.ClientConnInterface) ScrapperAPIClient {
	return &scrapperAPIClient{cc}
}

func (c *scrapperAPIClient) RegisterChat(ctx context.Context, in *RegisterChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPI_RegisterChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIClient) DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPI_DeleteChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIClient) GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, ScrapperAPI_GetLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIClient) AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, ScrapperAPI_AddLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIClient) RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, ScrapperAPI_RemoveLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapperAPIServer is the server API for ScrapperAPI service.
// All implementations must embed UnimplementedScrapperAPIServer
// for forward compatibility.
type ScrapperAPIServer interface {
	RegisterChat(context.Context, *RegisterChatRequest) (*emptypb.Empty, error)
	DeleteChat(context.Context, *DeleteChatRequest) (*emptypb.Empty, error)
	GetLinks(context.Context, *GetLinksRequest) (*ListLinksResponse, error)
	AddLink(context.Context, *AddLinkRequest) (*LinkResponse, error)
	RemoveLink(context.Context, *RemoveLinkRequest) (*LinkResponse, error)
	mustEmbedUnimplementedScrapperAPIServer()
}

// UnimplementedScrapperAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrapperAPIServer struct{}

func (UnimplementedScrapperAPIServer) RegisterChat(context.Context, *RegisterChatRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterChat not implemented")
}
func (UnimplementedScrapperAPIServer) DeleteChat(context.Context, *DeleteChatRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedScrapperAPIServer) GetLinks(context.Context, *GetLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinks not implemented")
}
func (UnimplementedScrapperAPIServer) AddLink(context.Context, *AddLinkRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLink not implemented")
}
func (UnimplementedScrapperAPIServer) RemoveLink(context.Context, *RemoveLinkRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveLink not implemented")
}
func (UnimplementedScrapperAPIServer) mustEmbedUnimplementedScrapperAPIServer() {}
func (UnimplementedScrapperAPIServer) testEmbeddedByValue()                     {}

// UnsafeScrapperAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapperAPIServer will
// result in compilation errors.
type UnsafeScrapperAPIServer interface {
	mustEmbedUnimplementedScrapperAPIServer()
}

func RegisterScrapperAPIServer(s grpc.ServiceRegistrar, srv ScrapperAPIServer) {
	// If the following call panics, it indicates UnimplementedScrapperAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrapperAPI_ServiceDesc, srv)
}

func _ScrapperAPI_RegisterChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServer).RegisterChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPI_RegisterChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServer).RegisterChat(ctx, req.(*RegisterChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPI_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPI_DeleteChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServer).DeleteChat(ctx, req.(*DeleteChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPI_GetLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServer).GetLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPI_GetLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServer).GetLinks(ctx, req.(*GetLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPI_AddLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServer).AddLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPI_AddLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServer).AddLink(ctx, req.(*AddLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPI_RemoveLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServer).RemoveLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPI_RemoveLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServer).RemoveLink(ctx, req.(*RemoveLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrapperAPI_ServiceDesc is the grpc.ServiceDesc for ScrapperAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapperAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrapper.ScrapperAPI",
	HandlerType: (*ScrapperAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChat",
			Handler:    _ScrapperAPI_RegisterChat_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _ScrapperAPI_DeleteChat_Handler,
		},
		{
			MethodName: "GetLinks",
			Handler:    _ScrapperAPI_GetLinks_Handler,
		},
		{
			MethodName: "AddLink",
			Handler:    _ScrapperAPI_AddLink_Handler,
		},
		{
			MethodName: "RemoveLink",
			Handler:    _ScrapperAPI_RemoveLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrapper-api.proto",
}
