services:
  scrapper:
    image: sid00r/link-tracker-scrapper:latest
    build: 
      context: .
      dockerfile: ./docker/scrapper/Dockerfile
    container_name: link-tracker-scrapper
    env_file:
      - .env
    networks:
      - markdown
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ready"]

  bot:
    image: sid00r/link-tracker-bot:latest
    build: 
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: link-tracker-bot
    env_file:
      - .env
    networks:
      - markdown
    restart: unless-stopped
    depends_on:
      scrapper:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - markdown
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: liquibase/liquibase:4.29
    depends_on:
      - db
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/$POSTGRES_DB
      - --username=$POSTGRES_USER
      - --password=$POSTGRES_PASSWORD
      - update
    volumes:
      - ./db/migrations:/changesets
    networks:
      - markdown

  kafka-1:
    image: docker.io/bitnamilegacy/kafka:latest
    environment:
      KAFKA_CLUSTER_ID: 0
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: "broker, controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-1:9093,1@kafka-2:9093,2@kafka-3:9093"
      KAFKA_CFG_LISTENERS: "BROKER://:9094,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://kafka-1:9094"
    networks:
      - markdown
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka-1:9094 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s

  kafka-2:
    image: docker.io/bitnamilegacy/kafka:latest
    environment:
      KAFKA_CLUSTER_ID: 0
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker, controller"
      KAFKA_CFG_LISTENERS: "BROKER://:9094,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://kafka-2:9094"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-1:9093,1@kafka-2:9093,2@kafka-3:9093"
    networks:
      - markdown
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka-2:9094 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s

  kafka-3:
    image: docker.io/bitnamilegacy/kafka:latest
    environment:
      KAFKA_CLUSTER_ID: 0
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: "broker, controller"
      KAFKA_CFG_LISTENERS: "BROKER://:9094,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://kafka-3:9094"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-1:9093,1@kafka-2:9093,2@kafka-3:9093"
    networks:
      - markdown
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka-3:9094 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s

  valkey:
    image: bitnami/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    environment:
      - VALKEY_PASSWORD=$VALKEY_PASSWORD
    networks:
      - markdown
    volumes:
      - valkeydata:/bitnami/valkey
    restart: unless-stopped

networks:
  markdown:
    driver: bridge

volumes:
  pgdata:
  valkeydata:
