services:
  scrapper:
    image: sid00r/link-tracker-scrapper:latest
    build: 
      context: .
      dockerfile: ./docker/scrapper/Dockerfile
    container_name: link-tracker-scrapper
    environment:
      - SCRAPPER_SERVER_ADDR=$SCRAPPER_SERVER_ADDR
      - BOT_SERVER_ADDR=$BOT_SERVER_ADDR
      - CONFIG_FILE=$CONFIG_FILE
    ports:
      - "1234:1234"
    networks:
      - markdown
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  bot:
    image: sid00r/link-tracker-bot:latest
    build: 
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: link-tracker-bot
    environment:
      - SCRAPPER_SERVER_ADDR=$SCRAPPER_SERVER_ADDR
      - BOT_SERVER_ADDR=$BOT_SERVER_ADDR
      - CONFIG_FILE=$CONFIG_FILE
    ports:
      - "1235:1235"
    networks:
      - markdown
    restart: unless-stopped
    depends_on:
     - scrapper

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: $APP_POSTGRES_USER
      POSTGRES_PASSWORD: $APP_POSTGRES_PASSWORD
      POSTGRES_DB: $APP_POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - markdown
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: liquibase/liquibase:4.29
    depends_on:
      - db
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/$APP_POSTGRES_DB
      - --username=$APP_POSTGRES_USER
      - --password=$APP_POSTGRES_PASSWORD
      - update
    volumes:
      - ./db/migrations:/changesets
    networks:
      - markdown

networks:
  markdown:
    driver: bridge

volumes:
  pgdata: