// Code generated by MockGen. DO NOT EDIT.
// Source: scrapper.go
//
// Generated by this command:
//
//	mockgen -source=scrapper.go -destination=mocks/mock.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScrapper is a mock of Scrapper interface.
type MockScrapper struct {
	ctrl     *gomock.Controller
	recorder *MockScrapperMockRecorder
	isgomock struct{}
}

// MockScrapperMockRecorder is the mock recorder for MockScrapper.
type MockScrapperMockRecorder struct {
	mock *MockScrapper
}

// NewMockScrapper creates a new mock instance.
func NewMockScrapper(ctrl *gomock.Controller) *MockScrapper {
	mock := &MockScrapper{ctrl: ctrl}
	mock.recorder = &MockScrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapper) EXPECT() *MockScrapperMockRecorder {
	return m.recorder
}

// GetUpdate mocks base method.
func (m *MockScrapper) GetUpdate(arg0 string) (*domain.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdate", arg0)
	ret0, _ := ret[0].(*domain.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdate indicates an expected call of GetUpdate.
func (mr *MockScrapperMockRecorder) GetUpdate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdate", reflect.TypeOf((*MockScrapper)(nil).GetUpdate), arg0)
}
