// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/scrapper-api.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tg_Chat_Id    int64                  `protobuf:"varint,1,opt,name=Tg_Chat_Id,json=TgChatId,proto3" json:"Tg_Chat_Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinksRequest) Reset() {
	*x = DeleteLinksRequest{}
	mi := &file_proto_scrapper_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinksRequest) ProtoMessage() {}

func (x *DeleteLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinksRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_api_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteLinksRequest) GetTg_Chat_Id() int64 {
	if x != nil {
		return x.Tg_Chat_Id
	}
	return 0
}

type DeleteTgChatIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTgChatIdRequest) Reset() {
	*x = DeleteTgChatIdRequest{}
	mi := &file_proto_scrapper_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTgChatIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTgChatIdRequest) ProtoMessage() {}

func (x *DeleteTgChatIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTgChatIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteTgChatIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_api_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTgChatIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tg_Chat_Id    int64                  `protobuf:"varint,1,opt,name=Tg_Chat_Id,json=TgChatId,proto3" json:"Tg_Chat_Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinksRequest) Reset() {
	*x = GetLinksRequest{}
	mi := &file_proto_scrapper_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinksRequest) ProtoMessage() {}

func (x *GetLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinksRequest.ProtoReflect.Descriptor instead.
func (*GetLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetLinksRequest) GetTg_Chat_Id() int64 {
	if x != nil {
		return x.Tg_Chat_Id
	}
	return 0
}

type PostLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tg_Chat_Id    int64                  `protobuf:"varint,1,opt,name=Tg_Chat_Id,json=TgChatId,proto3" json:"Tg_Chat_Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLinksRequest) Reset() {
	*x = PostLinksRequest{}
	mi := &file_proto_scrapper_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLinksRequest) ProtoMessage() {}

func (x *PostLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLinksRequest.ProtoReflect.Descriptor instead.
func (*PostLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_api_proto_rawDescGZIP(), []int{3}
}

func (x *PostLinksRequest) GetTg_Chat_Id() int64 {
	if x != nil {
		return x.Tg_Chat_Id
	}
	return 0
}

type PostTgChatIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTgChatIdRequest) Reset() {
	*x = PostTgChatIdRequest{}
	mi := &file_proto_scrapper_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTgChatIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTgChatIdRequest) ProtoMessage() {}

func (x *PostTgChatIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTgChatIdRequest.ProtoReflect.Descriptor instead.
func (*PostTgChatIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_api_proto_rawDescGZIP(), []int{4}
}

func (x *PostTgChatIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_scrapper_api_proto protoreflect.FileDescriptor

const file_proto_scrapper_api_proto_rawDesc = "" +
	"\n" +
	"\x18proto/scrapper-api.proto\x12\vscrapperapi\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\x12DeleteLinksRequest\x12\x1c\n" +
	"\n" +
	"Tg_Chat_Id\x18\x01 \x01(\x03R\bTgChatId\"'\n" +
	"\x15DeleteTgChatIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x0fGetLinksRequest\x12\x1c\n" +
	"\n" +
	"Tg_Chat_Id\x18\x01 \x01(\x03R\bTgChatId\"0\n" +
	"\x10PostLinksRequest\x12\x1c\n" +
	"\n" +
	"Tg_Chat_Id\x18\x01 \x01(\x03R\bTgChatId\"%\n" +
	"\x13PostTgChatIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xd8\x03\n" +
	"\x12ScrapperAPIService\x12V\n" +
	"\vDeleteLinks\x12\x1f.scrapperapi.DeleteLinksRequest\x1a\x16.google.protobuf.Empty\"\x0e\x82\xd3\xe4\x93\x02\b*\x06/links\x12c\n" +
	"\x0eDeleteTgChatId\x12\".scrapperapi.DeleteTgChatIdRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/tg-chat/{id}\x12P\n" +
	"\bGetLinks\x12\x1c.scrapperapi.GetLinksRequest\x1a\x16.google.protobuf.Empty\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/links\x12R\n" +
	"\tPostLinks\x12\x1d.scrapperapi.PostLinksRequest\x1a\x16.google.protobuf.Empty\"\x0e\x82\xd3\xe4\x93\x02\b\"\x06/links\x12_\n" +
	"\fPostTgChatId\x12 .scrapperapi.PostTgChatIdRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f\"\r/tg-chat/{id}B\x1cZ\x1ainternal/api/scrapper/gRPCb\x06proto3"

var (
	file_proto_scrapper_api_proto_rawDescOnce sync.Once
	file_proto_scrapper_api_proto_rawDescData []byte
)

func file_proto_scrapper_api_proto_rawDescGZIP() []byte {
	file_proto_scrapper_api_proto_rawDescOnce.Do(func() {
		file_proto_scrapper_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scrapper_api_proto_rawDesc), len(file_proto_scrapper_api_proto_rawDesc)))
	})
	return file_proto_scrapper_api_proto_rawDescData
}

var file_proto_scrapper_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_scrapper_api_proto_goTypes = []any{
	(*DeleteLinksRequest)(nil),    // 0: scrapperapi.DeleteLinksRequest
	(*DeleteTgChatIdRequest)(nil), // 1: scrapperapi.DeleteTgChatIdRequest
	(*GetLinksRequest)(nil),       // 2: scrapperapi.GetLinksRequest
	(*PostLinksRequest)(nil),      // 3: scrapperapi.PostLinksRequest
	(*PostTgChatIdRequest)(nil),   // 4: scrapperapi.PostTgChatIdRequest
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_proto_scrapper_api_proto_depIdxs = []int32{
	0, // 0: scrapperapi.ScrapperAPIService.DeleteLinks:input_type -> scrapperapi.DeleteLinksRequest
	1, // 1: scrapperapi.ScrapperAPIService.DeleteTgChatId:input_type -> scrapperapi.DeleteTgChatIdRequest
	2, // 2: scrapperapi.ScrapperAPIService.GetLinks:input_type -> scrapperapi.GetLinksRequest
	3, // 3: scrapperapi.ScrapperAPIService.PostLinks:input_type -> scrapperapi.PostLinksRequest
	4, // 4: scrapperapi.ScrapperAPIService.PostTgChatId:input_type -> scrapperapi.PostTgChatIdRequest
	5, // 5: scrapperapi.ScrapperAPIService.DeleteLinks:output_type -> google.protobuf.Empty
	5, // 6: scrapperapi.ScrapperAPIService.DeleteTgChatId:output_type -> google.protobuf.Empty
	5, // 7: scrapperapi.ScrapperAPIService.GetLinks:output_type -> google.protobuf.Empty
	5, // 8: scrapperapi.ScrapperAPIService.PostLinks:output_type -> google.protobuf.Empty
	5, // 9: scrapperapi.ScrapperAPIService.PostTgChatId:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scrapper_api_proto_init() }
func file_proto_scrapper_api_proto_init() {
	if File_proto_scrapper_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scrapper_api_proto_rawDesc), len(file_proto_scrapper_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scrapper_api_proto_goTypes,
		DependencyIndexes: file_proto_scrapper_api_proto_depIdxs,
		MessageInfos:      file_proto_scrapper_api_proto_msgTypes,
	}.Build()
	File_proto_scrapper_api_proto = out.File
	file_proto_scrapper_api_proto_goTypes = nil
	file_proto_scrapper_api_proto_depIdxs = nil
}
