// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/scrapper-api.proto

package rpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrapperAPIService_DeleteLinks_FullMethodName    = "/scrapperapi.ScrapperAPIService/DeleteLinks"
	ScrapperAPIService_DeleteTgChatId_FullMethodName = "/scrapperapi.ScrapperAPIService/DeleteTgChatId"
	ScrapperAPIService_GetLinks_FullMethodName       = "/scrapperapi.ScrapperAPIService/GetLinks"
	ScrapperAPIService_PostLinks_FullMethodName      = "/scrapperapi.ScrapperAPIService/PostLinks"
	ScrapperAPIService_PostTgChatId_FullMethodName   = "/scrapperapi.ScrapperAPIService/PostTgChatId"
)

// ScrapperAPIServiceClient is the client API for ScrapperAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapperAPIServiceClient interface {
	// Убрать отслеживание ссылки
	DeleteLinks(ctx context.Context, in *DeleteLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Удалить чат
	DeleteTgChatId(ctx context.Context, in *DeleteTgChatIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Получить все отслеживаемые ссылки
	GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Добавить отслеживание ссылки
	PostLinks(ctx context.Context, in *PostLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Зарегистрировать чат
	PostTgChatId(ctx context.Context, in *PostTgChatIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type scrapperAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperAPIServiceClient(cc grpc.ClientConnInterface) ScrapperAPIServiceClient {
	return &scrapperAPIServiceClient{cc}
}

func (c *scrapperAPIServiceClient) DeleteLinks(ctx context.Context, in *DeleteLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPIService_DeleteLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIServiceClient) DeleteTgChatId(ctx context.Context, in *DeleteTgChatIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPIService_DeleteTgChatId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIServiceClient) GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPIService_GetLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIServiceClient) PostLinks(ctx context.Context, in *PostLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPIService_PostLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperAPIServiceClient) PostTgChatId(ctx context.Context, in *PostTgChatIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperAPIService_PostTgChatId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapperAPIServiceServer is the server API for ScrapperAPIService service.
// All implementations must embed UnimplementedScrapperAPIServiceServer
// for forward compatibility.
type ScrapperAPIServiceServer interface {
	// Убрать отслеживание ссылки
	DeleteLinks(context.Context, *DeleteLinksRequest) (*emptypb.Empty, error)
	// Удалить чат
	DeleteTgChatId(context.Context, *DeleteTgChatIdRequest) (*emptypb.Empty, error)
	// Получить все отслеживаемые ссылки
	GetLinks(context.Context, *GetLinksRequest) (*emptypb.Empty, error)
	// Добавить отслеживание ссылки
	PostLinks(context.Context, *PostLinksRequest) (*emptypb.Empty, error)
	// Зарегистрировать чат
	PostTgChatId(context.Context, *PostTgChatIdRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedScrapperAPIServiceServer()
}

// UnimplementedScrapperAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrapperAPIServiceServer struct{}

func (UnimplementedScrapperAPIServiceServer) DeleteLinks(context.Context, *DeleteLinksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLinks not implemented")
}
func (UnimplementedScrapperAPIServiceServer) DeleteTgChatId(context.Context, *DeleteTgChatIdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTgChatId not implemented")
}
func (UnimplementedScrapperAPIServiceServer) GetLinks(context.Context, *GetLinksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinks not implemented")
}
func (UnimplementedScrapperAPIServiceServer) PostLinks(context.Context, *PostLinksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PostLinks not implemented")
}
func (UnimplementedScrapperAPIServiceServer) PostTgChatId(context.Context, *PostTgChatIdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PostTgChatId not implemented")
}
func (UnimplementedScrapperAPIServiceServer) mustEmbedUnimplementedScrapperAPIServiceServer() {}
func (UnimplementedScrapperAPIServiceServer) testEmbeddedByValue()                            {}

// UnsafeScrapperAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapperAPIServiceServer will
// result in compilation errors.
type UnsafeScrapperAPIServiceServer interface {
	mustEmbedUnimplementedScrapperAPIServiceServer()
}

func RegisterScrapperAPIServiceServer(s grpc.ServiceRegistrar, srv ScrapperAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedScrapperAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrapperAPIService_ServiceDesc, srv)
}

func _ScrapperAPIService_DeleteLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServiceServer).DeleteLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPIService_DeleteLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServiceServer).DeleteLinks(ctx, req.(*DeleteLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPIService_DeleteTgChatId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTgChatIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServiceServer).DeleteTgChatId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPIService_DeleteTgChatId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServiceServer).DeleteTgChatId(ctx, req.(*DeleteTgChatIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPIService_GetLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServiceServer).GetLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPIService_GetLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServiceServer).GetLinks(ctx, req.(*GetLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPIService_PostLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServiceServer).PostLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPIService_PostLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServiceServer).PostLinks(ctx, req.(*PostLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperAPIService_PostTgChatId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTgChatIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperAPIServiceServer).PostTgChatId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperAPIService_PostTgChatId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperAPIServiceServer).PostTgChatId(ctx, req.(*PostTgChatIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrapperAPIService_ServiceDesc is the grpc.ServiceDesc for ScrapperAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapperAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrapperapi.ScrapperAPIService",
	HandlerType: (*ScrapperAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteLinks",
			Handler:    _ScrapperAPIService_DeleteLinks_Handler,
		},
		{
			MethodName: "DeleteTgChatId",
			Handler:    _ScrapperAPIService_DeleteTgChatId_Handler,
		},
		{
			MethodName: "GetLinks",
			Handler:    _ScrapperAPIService_GetLinks_Handler,
		},
		{
			MethodName: "PostLinks",
			Handler:    _ScrapperAPIService_PostLinks_Handler,
		},
		{
			MethodName: "PostTgChatId",
			Handler:    _ScrapperAPIService_PostTgChatId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scrapper-api.proto",
}
