// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/mock.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// AddChat mocks base method.
func (m *MockLinkRepository) AddChat(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChat indicates an expected call of AddChat.
func (mr *MockLinkRepositoryMockRecorder) AddChat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChat", reflect.TypeOf((*MockLinkRepository)(nil).AddChat), arg0)
}

// AddLink mocks base method.
func (m *MockLinkRepository) AddLink(arg0 int64, arg1 domain.Link) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinkRepositoryMockRecorder) AddLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinkRepository)(nil).AddLink), arg0, arg1)
}

// DeleteChat mocks base method.
func (m *MockLinkRepository) DeleteChat(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockLinkRepositoryMockRecorder) DeleteChat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockLinkRepository)(nil).DeleteChat), arg0)
}

// DeleteLink mocks base method.
func (m *MockLinkRepository) DeleteLink(arg0 int64, arg1 string) (*domain.LinkWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", arg0, arg1)
	ret0, _ := ret[0].(*domain.LinkWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkRepositoryMockRecorder) DeleteLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkRepository)(nil).DeleteLink), arg0, arg1)
}

// GetLinks mocks base method.
func (m *MockLinkRepository) GetLinks(arg0 int64) ([]domain.LinkWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", arg0)
	ret0, _ := ret[0].([]domain.LinkWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockLinkRepositoryMockRecorder) GetLinks(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockLinkRepository)(nil).GetLinks), arg0)
}

// MockLinkUpdateRepository is a mock of LinkUpdateRepository interface.
type MockLinkUpdateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkUpdateRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkUpdateRepositoryMockRecorder is the mock recorder for MockLinkUpdateRepository.
type MockLinkUpdateRepositoryMockRecorder struct {
	mock *MockLinkUpdateRepository
}

// NewMockLinkUpdateRepository creates a new mock instance.
func NewMockLinkUpdateRepository(ctrl *gomock.Controller) *MockLinkUpdateRepository {
	mock := &MockLinkUpdateRepository{ctrl: ctrl}
	mock.recorder = &MockLinkUpdateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkUpdateRepository) EXPECT() *MockLinkUpdateRepositoryMockRecorder {
	return m.recorder
}

// GetLinkBatch mocks base method.
func (m *MockLinkUpdateRepository) GetLinkBatch(arg0 int64) ([]domain.LinkUpdate, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkBatch", arg0)
	ret0, _ := ret[0].([]domain.LinkUpdate)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLinkBatch indicates an expected call of GetLinkBatch.
func (mr *MockLinkUpdateRepositoryMockRecorder) GetLinkBatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkBatch", reflect.TypeOf((*MockLinkUpdateRepository)(nil).GetLinkBatch), arg0)
}

// GetTimeAndUpdateLink mocks base method.
func (m *MockLinkUpdateRepository) GetTimeAndUpdateLink(arg0 string, arg1 time.Time) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeAndUpdateLink", arg0, arg1)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeAndUpdateLink indicates an expected call of GetTimeAndUpdateLink.
func (mr *MockLinkUpdateRepositoryMockRecorder) GetTimeAndUpdateLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeAndUpdateLink", reflect.TypeOf((*MockLinkUpdateRepository)(nil).GetTimeAndUpdateLink), arg0, arg1)
}

// MockLinkUnitedRepository is a mock of LinkUnitedRepository interface.
type MockLinkUnitedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkUnitedRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkUnitedRepositoryMockRecorder is the mock recorder for MockLinkUnitedRepository.
type MockLinkUnitedRepositoryMockRecorder struct {
	mock *MockLinkUnitedRepository
}

// NewMockLinkUnitedRepository creates a new mock instance.
func NewMockLinkUnitedRepository(ctrl *gomock.Controller) *MockLinkUnitedRepository {
	mock := &MockLinkUnitedRepository{ctrl: ctrl}
	mock.recorder = &MockLinkUnitedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkUnitedRepository) EXPECT() *MockLinkUnitedRepositoryMockRecorder {
	return m.recorder
}

// AddChat mocks base method.
func (m *MockLinkUnitedRepository) AddChat(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChat indicates an expected call of AddChat.
func (mr *MockLinkUnitedRepositoryMockRecorder) AddChat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChat", reflect.TypeOf((*MockLinkUnitedRepository)(nil).AddChat), arg0)
}

// AddLink mocks base method.
func (m *MockLinkUnitedRepository) AddLink(arg0 int64, arg1 domain.Link) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinkUnitedRepositoryMockRecorder) AddLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinkUnitedRepository)(nil).AddLink), arg0, arg1)
}

// DeleteChat mocks base method.
func (m *MockLinkUnitedRepository) DeleteChat(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockLinkUnitedRepositoryMockRecorder) DeleteChat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockLinkUnitedRepository)(nil).DeleteChat), arg0)
}

// DeleteLink mocks base method.
func (m *MockLinkUnitedRepository) DeleteLink(arg0 int64, arg1 string) (*domain.LinkWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", arg0, arg1)
	ret0, _ := ret[0].(*domain.LinkWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkUnitedRepositoryMockRecorder) DeleteLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkUnitedRepository)(nil).DeleteLink), arg0, arg1)
}

// GetLinkBatch mocks base method.
func (m *MockLinkUnitedRepository) GetLinkBatch(arg0 int64) ([]domain.LinkUpdate, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkBatch", arg0)
	ret0, _ := ret[0].([]domain.LinkUpdate)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLinkBatch indicates an expected call of GetLinkBatch.
func (mr *MockLinkUnitedRepositoryMockRecorder) GetLinkBatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkBatch", reflect.TypeOf((*MockLinkUnitedRepository)(nil).GetLinkBatch), arg0)
}

// GetLinks mocks base method.
func (m *MockLinkUnitedRepository) GetLinks(arg0 int64) ([]domain.LinkWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", arg0)
	ret0, _ := ret[0].([]domain.LinkWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockLinkUnitedRepositoryMockRecorder) GetLinks(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockLinkUnitedRepository)(nil).GetLinks), arg0)
}

// GetTimeAndUpdateLink mocks base method.
func (m *MockLinkUnitedRepository) GetTimeAndUpdateLink(arg0 string, arg1 time.Time) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeAndUpdateLink", arg0, arg1)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeAndUpdateLink indicates an expected call of GetTimeAndUpdateLink.
func (mr *MockLinkUnitedRepositoryMockRecorder) GetTimeAndUpdateLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeAndUpdateLink", reflect.TypeOf((*MockLinkUnitedRepository)(nil).GetTimeAndUpdateLink), arg0, arg1)
}
