// Code generated by MockGen. DO NOT EDIT.
// Source: chat.go
//
// Generated by this command:
//
//	mockgen -source=chat.go -destination=mocks/mock.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockBotApi is a mock of BotApi interface.
type MockBotApi struct {
	ctrl     *gomock.Controller
	recorder *MockBotApiMockRecorder
	isgomock struct{}
}

// MockBotApiMockRecorder is the mock recorder for MockBotApi.
type MockBotApiMockRecorder struct {
	mock *MockBotApi
}

// NewMockBotApi creates a new mock instance.
func NewMockBotApi(ctrl *gomock.Controller) *MockBotApi {
	mock := &MockBotApi{ctrl: ctrl}
	mock.recorder = &MockBotApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotApi) EXPECT() *MockBotApiMockRecorder {
	return m.recorder
}

// GetUpdatesChan mocks base method.
func (m *MockBotApi) GetUpdatesChan(arg0 tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan", arg0)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MockBotApiMockRecorder) GetUpdatesChan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MockBotApi)(nil).GetUpdatesChan), arg0)
}

// Request mocks base method.
func (m *MockBotApi) Request(arg0 tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", arg0)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockBotApiMockRecorder) Request(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockBotApi)(nil).Request), arg0)
}

// Send mocks base method.
func (m *MockBotApi) Send(arg0 tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockBotApiMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBotApi)(nil).Send), arg0)
}
