// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=mocks/mock.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// AddChat mocks base method.
func (m *MockAPI) AddChat(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChat indicates an expected call of AddChat.
func (mr *MockAPIMockRecorder) AddChat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChat", reflect.TypeOf((*MockAPI)(nil).AddChat), arg0)
}

// AddLink mocks base method.
func (m *MockAPI) AddLink(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockAPIMockRecorder) AddLink(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockAPI)(nil).AddLink), arg0)
}

// DeleteChat mocks base method.
func (m *MockAPI) DeleteChat(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockAPIMockRecorder) DeleteChat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockAPI)(nil).DeleteChat), arg0)
}

// DeleteLink mocks base method.
func (m *MockAPI) DeleteLink(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockAPIMockRecorder) DeleteLink(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockAPI)(nil).DeleteLink), arg0)
}

// GetData mocks base method.
func (m *MockAPI) GetData(arg0 int64) (domain.ChatData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", arg0)
	ret0, _ := ret[0].(domain.ChatData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockAPIMockRecorder) GetData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockAPI)(nil).GetData), arg0)
}

// GetLinks mocks base method.
func (m *MockAPI) GetLinks(arg0 int64, arg1 string) ([]domain.LinkWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", arg0, arg1)
	ret0, _ := ret[0].([]domain.LinkWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockAPIMockRecorder) GetLinks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockAPI)(nil).GetLinks), arg0, arg1)
}

// LogError mocks base method.
func (m *MockAPI) LogError(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogError", arg0)
}

// LogError indicates an expected call of LogError.
func (mr *MockAPIMockRecorder) LogError(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockAPI)(nil).LogError), arg0)
}

// Send mocks base method.
func (m *MockAPI) Send(arg0 int64, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0, arg1)
}

// Send indicates an expected call of Send.
func (mr *MockAPIMockRecorder) Send(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAPI)(nil).Send), arg0, arg1)
}

// SetData mocks base method.
func (m *MockAPI) SetData(arg0 int64, arg1 domain.ChatData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetData indicates an expected call of SetData.
func (mr *MockAPIMockRecorder) SetData(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetData", reflect.TypeOf((*MockAPI)(nil).SetData), arg0, arg1)
}

// SetTrackFilters mocks base method.
func (m *MockAPI) SetTrackFilters(arg0 int64, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrackFilters", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrackFilters indicates an expected call of SetTrackFilters.
func (mr *MockAPIMockRecorder) SetTrackFilters(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrackFilters", reflect.TypeOf((*MockAPI)(nil).SetTrackFilters), arg0, arg1)
}

// SetTrackLink mocks base method.
func (m *MockAPI) SetTrackLink(arg0 int64, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrackLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrackLink indicates an expected call of SetTrackLink.
func (mr *MockAPIMockRecorder) SetTrackLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrackLink", reflect.TypeOf((*MockAPI)(nil).SetTrackLink), arg0, arg1)
}

// SetTrackTags mocks base method.
func (m *MockAPI) SetTrackTags(arg0 int64, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrackTags", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrackTags indicates an expected call of SetTrackTags.
func (mr *MockAPIMockRecorder) SetTrackTags(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrackTags", reflect.TypeOf((*MockAPI)(nil).SetTrackTags), arg0, arg1)
}

// SetUntrackLink mocks base method.
func (m *MockAPI) SetUntrackLink(arg0 int64, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUntrackLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUntrackLink indicates an expected call of SetUntrackLink.
func (mr *MockAPIMockRecorder) SetUntrackLink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUntrackLink", reflect.TypeOf((*MockAPI)(nil).SetUntrackLink), arg0, arg1)
}

// StartTrack mocks base method.
func (m *MockAPI) StartTrack(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTrack", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTrack indicates an expected call of StartTrack.
func (mr *MockAPIMockRecorder) StartTrack(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTrack", reflect.TypeOf((*MockAPI)(nil).StartTrack), arg0)
}

// StopTrack mocks base method.
func (m *MockAPI) StopTrack(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopTrack", arg0)
}

// StopTrack indicates an expected call of StopTrack.
func (mr *MockAPIMockRecorder) StopTrack(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopTrack", reflect.TypeOf((*MockAPI)(nil).StopTrack), arg0)
}

// Wait mocks base method.
func (m *MockAPI) Wait(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockAPIMockRecorder) Wait(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockAPI)(nil).Wait), arg0)
}
