// Code generated by MockGen. DO NOT EDIT.
// Source: client.gen.go
//
// Generated by this command:
//
//	mockgen -source=client.gen.go -destination=mocks/mock.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	rest "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/pkg/api/scrapper/rest"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
	isgomock struct{}
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// DeleteLinks mocks base method.
func (m *MockClientInterface) DeleteLinks(ctx context.Context, params *rest.DeleteLinksParams, body rest.DeleteLinksJSONRequestBody, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteLinks", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLinks indicates an expected call of DeleteLinks.
func (mr *MockClientInterfaceMockRecorder) DeleteLinks(ctx, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinks", reflect.TypeOf((*MockClientInterface)(nil).DeleteLinks), varargs...)
}

// DeleteLinksWithBody mocks base method.
func (m *MockClientInterface) DeleteLinksWithBody(ctx context.Context, params *rest.DeleteLinksParams, contentType string, body io.Reader, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteLinksWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLinksWithBody indicates an expected call of DeleteLinksWithBody.
func (mr *MockClientInterfaceMockRecorder) DeleteLinksWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinksWithBody", reflect.TypeOf((*MockClientInterface)(nil).DeleteLinksWithBody), varargs...)
}

// DeleteTgChatId mocks base method.
func (m *MockClientInterface) DeleteTgChatId(ctx context.Context, id int64, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTgChatId", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTgChatId indicates an expected call of DeleteTgChatId.
func (mr *MockClientInterfaceMockRecorder) DeleteTgChatId(ctx, id any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTgChatId", reflect.TypeOf((*MockClientInterface)(nil).DeleteTgChatId), varargs...)
}

// GetLinks mocks base method.
func (m *MockClientInterface) GetLinks(ctx context.Context, params *rest.GetLinksParams, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLinks", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockClientInterfaceMockRecorder) GetLinks(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockClientInterface)(nil).GetLinks), varargs...)
}

// PostLinks mocks base method.
func (m *MockClientInterface) PostLinks(ctx context.Context, params *rest.PostLinksParams, body rest.PostLinksJSONRequestBody, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostLinks", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostLinks indicates an expected call of PostLinks.
func (mr *MockClientInterfaceMockRecorder) PostLinks(ctx, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostLinks", reflect.TypeOf((*MockClientInterface)(nil).PostLinks), varargs...)
}

// PostLinksWithBody mocks base method.
func (m *MockClientInterface) PostLinksWithBody(ctx context.Context, params *rest.PostLinksParams, contentType string, body io.Reader, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostLinksWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostLinksWithBody indicates an expected call of PostLinksWithBody.
func (mr *MockClientInterfaceMockRecorder) PostLinksWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostLinksWithBody", reflect.TypeOf((*MockClientInterface)(nil).PostLinksWithBody), varargs...)
}

// PostTgChatId mocks base method.
func (m *MockClientInterface) PostTgChatId(ctx context.Context, id int64, reqEditors ...rest.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostTgChatId", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTgChatId indicates an expected call of PostTgChatId.
func (mr *MockClientInterfaceMockRecorder) PostTgChatId(ctx, id any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTgChatId", reflect.TypeOf((*MockClientInterface)(nil).PostTgChatId), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// DeleteLinksWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteLinksWithBodyWithResponse(ctx context.Context, params *rest.DeleteLinksParams, contentType string, body io.Reader, reqEditors ...rest.RequestEditorFn) (*rest.DeleteLinksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteLinksWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.DeleteLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLinksWithBodyWithResponse indicates an expected call of DeleteLinksWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteLinksWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinksWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteLinksWithBodyWithResponse), varargs...)
}

// DeleteLinksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteLinksWithResponse(ctx context.Context, params *rest.DeleteLinksParams, body rest.DeleteLinksJSONRequestBody, reqEditors ...rest.RequestEditorFn) (*rest.DeleteLinksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteLinksWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.DeleteLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLinksWithResponse indicates an expected call of DeleteLinksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteLinksWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinksWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteLinksWithResponse), varargs...)
}

// DeleteTgChatIdWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteTgChatIdWithResponse(ctx context.Context, id int64, reqEditors ...rest.RequestEditorFn) (*rest.DeleteTgChatIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTgChatIdWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.DeleteTgChatIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTgChatIdWithResponse indicates an expected call of DeleteTgChatIdWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteTgChatIdWithResponse(ctx, id any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTgChatIdWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteTgChatIdWithResponse), varargs...)
}

// GetLinksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetLinksWithResponse(ctx context.Context, params *rest.GetLinksParams, reqEditors ...rest.RequestEditorFn) (*rest.GetLinksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLinksWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.GetLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinksWithResponse indicates an expected call of GetLinksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetLinksWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinksWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetLinksWithResponse), varargs...)
}

// PostLinksWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostLinksWithBodyWithResponse(ctx context.Context, params *rest.PostLinksParams, contentType string, body io.Reader, reqEditors ...rest.RequestEditorFn) (*rest.PostLinksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostLinksWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.PostLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostLinksWithBodyWithResponse indicates an expected call of PostLinksWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostLinksWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostLinksWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostLinksWithBodyWithResponse), varargs...)
}

// PostLinksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostLinksWithResponse(ctx context.Context, params *rest.PostLinksParams, body rest.PostLinksJSONRequestBody, reqEditors ...rest.RequestEditorFn) (*rest.PostLinksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostLinksWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.PostLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostLinksWithResponse indicates an expected call of PostLinksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostLinksWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostLinksWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostLinksWithResponse), varargs...)
}

// PostTgChatIdWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PostTgChatIdWithResponse(ctx context.Context, id int64, reqEditors ...rest.RequestEditorFn) (*rest.PostTgChatIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostTgChatIdWithResponse", varargs...)
	ret0, _ := ret[0].(*rest.PostTgChatIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTgChatIdWithResponse indicates an expected call of PostTgChatIdWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PostTgChatIdWithResponse(ctx, id any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTgChatIdWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PostTgChatIdWithResponse), varargs...)
}
